[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2.5",
    "django-crispy-forms>=2.4",
    "django-extensions>=4.1",
    "pillow>=11.3.0",
]
